version: '3.8'

services:
  TgSellerWebApp:
    # Это имя будет использоваться для сохранения образа после сборки.
    image: tg_seller_web_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seller-webapp
    ports:
      - "8080:8080"
    restart: unless-stopped
